# Generated by Django 5.1.6 on 2025-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'date_created'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the question in the quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='New Question', help_text='Enter your question here', verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='The correct answer for the question', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='For multiple choice questions, provide options as a JSON array', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('open_ended', 'Open Ended')], default='multiple_choice', max_length=50, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in seconds'),
        ),
    ]
