# Generated by Django 5.1.6 on 2025-02-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_options_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='join_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='QuizPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('is_host', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'fingerprint_hash')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time', models.FloatField(help_text='Time taken to answer in seconds')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('quiz_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizplayer')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
    ]
